# 4. IMDB_Classification_Preprocess_and_Training<a id='2_Data_wrangling'></a>

## 4.1 Table of Contents<a id='2.1_Contents'></a>
* 4. Bank_Churnrate_Preprocess_and_Training
  * 4.1 Table of Contents
  * 4.2 Introduction
  * 4.3 Imports
  * 4.4 Load Bank Churn Missing and Dropped Datasets
    * 4.4.1 Intial Loading and Assessments of Datasets
    * 4.4.2 Avoid Multicollineraty (Dummy Variable Trap)
  * 4.5 Create Train_Test Split & Preprocess Training Data
    * 4.5.1 Create Train_Test_Split
    * 4.5.2 Apply StandardScaler() for Training Data
  * 4.6 Save Data
  * 4.7 Summary

## 4.2 Introduction

Now that a thorough analysis as well as further cleaning and One-Hot enconding steps were implemented in prior EDA, train and test sets based on a usual 70/30 split will be created based on both the missing and dropped bank churn datasets for future steps in assessing model performance.

## 4.3 Imports<a id='2.3_Imports'></a>

Importing all appropriate packages in order to develop associated train and test sets for both imputed and dropped datasets for bank churn rate.

In [12]:
#Import pandas, matplotlib.pyplot, seaborn, and associated scikit learn methods and functions as well as random number for reproducibility
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import os
from PIL import Image
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
random_number = 42

## 4.4 Load Bank Churn Missing and Dropped Datasets

### 4.4.1 Intial Loading and Assessments of Datasets

In [2]:
#Loading associated datasets of dropped vs. missing datasets for movie_df_filtered.
path_file = 'C:/Users/tpooz/OneDrive/Desktop/Data_Science_BootCamp_2023/SpringBoard_Github/IMDB_Classification/0_Datasets/movie_df_filtered.csv'
movie_df_filtered = pd.read_csv(path_file, index_col=0)

Auditing the datasets with .info() and .head() displaying the first few records.

In [3]:
#.info() on bank_missing_df and bank_dropped_df to see a summary of the data
movie_df_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3939 entries, 0 to 3971
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       3939 non-null   object
 1   image    3939 non-null   object
 2   title    3939 non-null   object
 3   Genre_1  3939 non-null   object
 4   Genre_2  3939 non-null   object
 5   Genre_3  3939 non-null   object
dtypes: object(6)
memory usage: 215.4+ KB

In [4]:
#head method on bank_missing_df and bank_dropped_df to print the first several rows of the data
movie_df_filtered.head()

,id,image,title,Genre_1,Genre_2,Genre_3
0,tt0099785,https://m.media-amazon.com/images/M/MV5BMzFkM2...,Home Alone,Comedy,Family,None
1,tt0100944,https://m.media-amazon.com/images/M/MV5BMjI1MD...,The Witches,Adventure,Comedy,Family
2,tt0099810,https://m.media-amazon.com/images/M/MV5BZDdkOD...,The Hunt for Red October,Action,Adventure,Thriller
3,tt0099088,https://m.media-amazon.com/images/M/MV5BYjhlMG...,Back to the Future Part III,Adventure,Comedy,Sci-Fi
4,tt0100419,https://m.media-amazon.com/images/M/MV5BYzk3NG...,Problem Child,Comedy,Family,None

In [5]:
movie_df_filtered.shape

(3939, 6)

### 4.4.2 Avoid Multicollineraty (Dummy Variable Trap)

In order to avoid the dummy variable trap or potentially having issues with the feautres because of multicollineraty within the dummy variables, the different one-hot enconded categorical varibles will have k-1 features (where k is the number of unique categories within the variable). The baseline values will be values of the categories that occur most frequently in the respective categorical variable (ex. Card_Category_Blue). 

Further information and reference for the above paragraph found on: https://www.statology.org/dummy-variable-trap/

In [80]:
movie_dummy_1 = movie_df_filtered[['id','Genre_1', 'Genre_2', 'Genre_3']]
movie_dummy = pd.get_dummies(movie_dummy_1, columns = ['Genre_1','Genre_2','Genre_3'])
movie_dummy.head()

,id,Genre_1_Action,Genre_1_Adventure,Genre_1_Animation,Genre_1_Biography,Genre_1_Comedy,Genre_1_Crime,Genre_1_Documentary,Genre_1_Drama,Genre_1_Family,...,Genre_3_ Musical,Genre_3_ Mystery,Genre_3_ News,Genre_3_ Romance,Genre_3_ Sci-Fi,Genre_3_ Sport,Genre_3_ Thriller,Genre_3_ War,Genre_3_ Western,Genre_3_None
0,tt0099785,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,tt0100944,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,tt0099810,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,tt0099088,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,tt0100419,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [35]:
shape = (500,500)
img = Image.open('C:/Users/tpooz/OneDrive/Desktop/Data_Science_BootCamp_2023/SpringBoard_Github/IMDB_Classification/0_Datasets/Image_1/Image_1/tt3205010.jpg')
print(img.filename)
img_re = img.resize(shape)
img_re.show()
img_array = np.asarray(img_re)

C:/Users/tpooz/OneDrive/Desktop/Data_Science_BootCamp_2023/SpringBoard_Github/IMDB_Classification/0_Datasets/Image_1/Image_1/tt3205010.jpg

In [38]:
img_2 = Image.open('C:/Users/tpooz/OneDrive/Desktop/Data_Science_BootCamp_2023/SpringBoard_Github/IMDB_Classification/0_Datasets/Image_1/Image_1/tt3210796.jpg')
img2_re = img_2.resize(shape)
img2_re.show()
img_2array = np.asarray(img2_re)
img_2array

array([[[122, 153, 158],
        [121, 153, 158],
        [123, 153, 159],
        ...,
        [101, 129, 144],
        [ 80, 109, 127],
        [168, 179, 186]],

       [[123, 151, 157],
        [122, 151, 157],
        [123, 151, 157],
        ...,
        [ 90, 119, 136],
        [ 70,  99, 118],
        [166, 177, 183]],

       [[121, 150, 156],
        [121, 150, 156],
        [123, 150, 157],
        ...,
        [ 89, 117, 136],
        [ 69,  97, 118],
        [165, 175, 183]],

       ...,

       [[ 35,  53,  67],
        [ 35,  53,  67],
        [ 35,  53,  67],
        ...,
        [ 35,  52,  66],
        [ 30,  48,  63],
        [156, 163, 169]],

       [[ 35,  53,  67],
        [ 35,  53,  67],
        [ 35,  53,  67],
        ...,
        [ 35,  52,  66],
        [ 30,  48,  63],
        [156, 163, 169]],

       [[ 35,  53,  67],
        [ 35,  53,  67],
        [ 35,  53,  67],
        ...,
        [ 35,  52,  66],
        [ 30,  48,  63],
        [156, 163, 169]]], dtype=uint8)

In [86]:
def image_open(path):
    shape = (500,500)
    img = Image.open(path)
    img_re = img.resize(shape)
    color = img_re.convert("RGB")
    img_array = np.asarray(color.getdata())
    image_df = pd.DataFrame(img_array, columns=["red", "green", "blue"])
    image_df = pd.DataFrame(img_array)
    return image_df

In [87]:
image = image_open('C:/Users/tpooz/OneDrive/Desktop/Data_Science_BootCamp_2023/SpringBoard_Github/IMDB_Classification/0_Datasets/Image_1/Image_1/tt3205010.jpg')
image

          0    1    2
0       224  232  253
1       118  174  253
2       125  175  253
3       125  176  250
4       127  174  254
...     ...  ...  ...
249995  254  219  153
249996  254  219  152
249997  253  218  148
249998  253  222  156
249999  251  243  220

[250000 rows x 3 columns]

In [88]:
path = 'C:/Users/tpooz/OneDrive/Desktop/Data_Science_BootCamp_2023/SpringBoard_Github/IMDB_Classification/0_Datasets/Image_1/Image_1'
image_data = []
movie_genre = []
for i in os.listdir(path):
    if i.endswith(".jpg"):
        image_data.append(image_open(f"{path}/{i}"))
        movie_genre.append(i)

C:\Users\tpooz\anaconda3\lib\site-packages\PIL\Image.py:3167: DecompressionBombWarning: Image size (97200000 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(
C:\Users\tpooz\anaconda3\lib\site-packages\PIL\Image.py:3167: DecompressionBombWarning: Image size (99630000 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(
C:\Users\tpooz\anaconda3\lib\site-packages\PIL\Image.py:3167: DecompressionBombWarning: Image size (97159804 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(
C:\Users\tpooz\anaconda3\lib\site-packages\PIL\Image.py:3167: DecompressionBombWarning: Image size (97472122 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(
C:\Users\tpooz\anaconda3\lib\site-packages\PIL\Image.py:3167: DecompressionBombWarning: Image size (97200000 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(
C:\Users\tpooz\anaconda3\lib\site-packages\PIL\Image.py:3167: DecompressionBombWarning: Image size (97653348 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(
C:\Users\tpooz\anaconda3\lib\site-packages\PIL\Image.py:3167: DecompressionBombWarning: Image size (94770000 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(
C:\Users\tpooz\anaconda3\lib\site-packages\PIL\Image.py:3167: DecompressionBombWarning: Image size (97653348 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(
C:\Users\tpooz\anaconda3\lib\site-packages\PIL\Image.py:3167: DecompressionBombWarning: Image size (94770000 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(
C:\Users\tpooz\anaconda3\lib\site-packages\PIL\Image.py:3167: DecompressionBombWarning: Image size (97200000 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(
C:\Users\tpooz\anaconda3\lib\site-packages\PIL\Image.py:3167: DecompressionBombWarning: Image size (97658071 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(
C:\Users\tpooz\anaconda3\lib\site-packages\PIL\Image.py:3167: DecompressionBombWarning: Image size (98713125 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(
C:\Users\tpooz\anaconda3\lib\site-packages\PIL\Image.py:3167: DecompressionBombWarning: Image size (97200000 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(
C:\Users\tpooz\anaconda3\lib\site-packages\PIL\Image.py:3167: DecompressionBombWarning: Image size (97200000 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(
C:\Users\tpooz\anaconda3\lib\site-packages\PIL\Image.py:3167: DecompressionBombWarning: Image size (97200000 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(
C:\Users\tpooz\anaconda3\lib\site-packages\PIL\Image.py:3167: DecompressionBombWarning: Image size (97200000 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(
C:\Users\tpooz\anaconda3\lib\site-packages\PIL\Image.py:3167: DecompressionBombWarning: Image size (97653348 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(
C:\Users\tpooz\anaconda3\lib\site-packages\PIL\Image.py:3167: DecompressionBombWarning: Image size (98125500 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(
C:\Users\tpooz\anaconda3\lib\site-packages\PIL\Image.py:3167: DecompressionBombWarning: Image size (98599270 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(
C:\Users\tpooz\anaconda3\lib\site-packages\PIL\Image.py:3167: DecompressionBombWarning: Image size (100237500 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(
C:\Users\tpooz\anaconda3\lib\site-packages\PIL\Image.py:3167: DecompressionBombWarning: Image size (97200000 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(
C:\Users\tpooz\anaconda3\lib\site-packages\PIL\Image.py:3167: DecompressionBombWarning: Image size (97200000 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(

In [89]:
image_data

[        0   1   2
 0       8  21  27
 1       8  21  27
 2       8  21  27
 3       8  21  27
 4       8  21  27
 ...    ..  ..  ..
 249995  6  22  32
 249996  7  23  32
 249997  7  23  33
 249998  8  24  33
 249999  8  24  33

 [250000 rows x 3 columns],
          0   1   2
 0       69  58  38
 1       72  61  41
 2       73  62  42
 3       73  62  42
 4       69  58  38
 ...     ..  ..  ..
 249995   0   0   0
 249996   0   0   0
 249997   0   0   0
 249998   0   0   0
 249999   0   0   0

 [250000 rows x 3 columns],
           0    1    2
 0       112  236  254
 1       117  236  254
 2       118  238  255
 3       120  238  254
 4       118  239  253
 ...     ...  ...  ...
 249995   54   11    1
 249996   64   10    1
 249997   55   18    3
 249998   63   19    2
 249999   73   17    2

 [250000 rows x 3 columns],
          0   1   2
 0       58  51  90
 1       58  52  91
 2       58  52  90
 3       57  52  90
 4       57  52  90
 ...     ..  ..  ..
 249995  10   5   3
 249996  10   5   2
 249997  13   7   3
 249998  16   8   3
 249999  21  10   4

 [250000 rows x 3 columns],
           0   1   2
 0       118  29  20
 1       119  30  21
 2       117  28  19
 3       118  29  20
 4       121  31  22
 ...     ...  ..  ..
 249995   18   9  10
 249996   19   9   9
 249997   18   9   9
 249998   18   9   8
 249999   19   9   9

 [250000 rows x 3 columns],
         0  1  2
 0       0  0  0
 1       0  0  0
 2       0  0  0
 3       0  0  0
 4       0  0  0
 ...    .. .. ..
 249995  0  0  0
 249996  0  0  0
 249997  0  0  0
 249998  0  0  0
 249999  0  0  0

 [250000 rows x 3 columns],
           0    1    2
 0       162  211  239
 1       162  212  239
 2       164  212  240
 3       163  210  238
 4       164  209  238
 ...     ...  ...  ...
 249995   40   43   22
 249996   18   21    7
 249997   34   36   22
 249998   68   74   38
 249999   38   45   10

 [250000 rows x 3 columns],
           0    1    2
 0        33   66  107
 1        33   66  107
 2        33   66  107
 3        33   66  107
 4        33   66  107
 ...     ...  ...  ...
 249995   93  137   39
 249996  101  145   45
 249997   99  144   43
 249998   93  137   36
 249999   89  130   28

 [250000 rows x 3 columns],
          0   1   2
 0       40  23  77
 1       39  22  76
 2       39  20  75
 3       42  23  78
 4       43  24  77
 ...     ..  ..  ..
 249995  24  24  49
 249996  24  25  48
 249997  24  26  51
 249998  23  25  47
 249999  25  26  46

 [250000 rows x 3 columns],
          0    1    2
 0       16  151  211
 1       10  151  212
 2        6  150  211
 3        3  150  210
 4        5  151  211
 ...     ..  ...  ...
 249995  27  191  222
 249996  17  190  219
 249997  10  189  219
 249998  13  190  220
 249999   9  190  220

 [250000 rows x 3 columns],
         0    1    2
 0       2  156  215
 1       3  157  217
 2       2  159  219
 3       3  159  219
 4       2  159  220
 ...    ..  ...  ...
 249995  1  124   70
 249996  2  125   70
 249997  1  125   71
 249998  2  124   70
 249999  3  122   70

 [250000 rows x 3 columns],
          0   1  2
 0        1  19  1
 1        1  18  0
 2        5  20  3
 3        8  21  5
 4        3  17  1
 ...     ..  .. ..
 249995  23   2  1
 249996  27   5  3
 249997  24   2  1
 249998  26   5  2
 249999  22   2  0

 [250000 rows x 3 columns],
           0    1    2
 0        57   42   41
 1        60   43   43
 2        60   43   43
 3        57   42   42
 4        58   42   42
 ...     ...  ...  ...
 249995  192  203  210
 249996  192  203  211
 249997  191  203  212
 249998  190  203  210
 249999  190  203  210

 [250000 rows x 3 columns],
          0   1   2
 0       21  13  11
 1       21  13  10
 2       23  15  12
 3       24  16  10
 4       26  17   9
 ...     ..  ..  ..
 249995   8   8   8
 249996   7   7   7
 249997   9   9   9
 249998   9   9   9
 249999   9   9   9

 [250000 rows x 3 columns],
          0   1   2
 0       16   6   5
 1       14   5   4
 2       12   6   3
 3       11   6   3
 4       13   8   4
 ...     ..  ..  ..
 249995  88  40  26
 249996  88  40  26
 249997  88  40  26
 249998  86  38  24
 249999  85  37  23

 [250000 rows x 3 columns],
          0   1   2
 0       14  23  27
 1       14  24  26
 2       14  24  26
 3       14  24  26
 4       14  24  27
 ...     ..  ..  ..
 249995  13  23  28
 249996  14  23  28
 249997  13  23  28
 249998  13  23  28
 249999  13  23  27

 [250000 rows x 3 columns],
           0    1   2
 0        91  149  62
 1        85  137  57
 2       108  173  68
 3       123  193  76
 4       128  197  83
 ...     ...  ...  ..
 249995   42   75  26
 249996   45   77  29
 249997   43   76  27
 249998   39   68  25
 249999   35   61  22

 [250000 rows x 3 columns],
           0    1    2
 0       230  216  203
 1       230  216  203
 2       229  215  202
 3       230  216  203
 4       231  217  204
 ...     ...  ...  ...
 249995  230  216  203
 249996  230  216  203
 249997  230  216  203
 249998  230  216  203
 249999  230  216  203

 [250000 rows x 3 columns],
           0    1   2
 0        10   22  31
 1        10   22  32
 2         9   21  29
 3         9   20  28
 4         9   20  28
 ...     ...  ...  ..
 249995    8    1   6
 249996  111   66   4
 249997  185  109   4
 249998  196  135   4
 249999  208  152   6

 [250000 rows x 3 columns],
           0    1    2
 0        39   58  128
 1        39   58  128
 2        39   58  128
 3        39   58  128
 4        37   60  130
 ...     ...  ...  ...
 249995  149   83   51
 249996  156   87   53
 249997  153   85   50
 249998  161   93   56
 249999  170  102   63

 [250000 rows x 3 columns],
           0    1    2
 0       255  255  255
 1       255  255  255
 2       255  255  255
 3       255  255  255
 4       255  255  255
 ...     ...  ...  ...
 249995  255  255  255
 249996  255  255  255
 249997  255  255  255
 249998  255  255  255
 249999  255  255  255

 [250000 rows x 3 columns],
          0  1  2
 0       23  2  1
 1       23  2  1
 2       23  2  1
 3       23  2  1
 4       23  2  1
 ...     .. .. ..
 249995   0  0  0
 249996   0  0  0
 249997   0  0  0
 249998   0  0  0
 249999   0  0  0

 [250000 rows x 3 columns],
          0    1    2
 0        0   45   71
 1       81  162  189
 2       71  187  220
 3       46  189  229
 4       39  194  241
 ...     ..  ...  ...
 249995   0   42   60
 249996   2   40   56
 249997  11   39   52
 249998  21   32   41
 249999  33   35   40

 [250000 rows x 3 columns],
           0    1    2
 0       195  155  130
 1       191  151  126
 2       185  146  121
 3       190  153  127
 4       190  153  127
 ...     ...  ...  ...
 249995   86   61   36
 249996   91   64   40
 249997   81   56   33
 249998   63   41   20
 249999   64   43   25

 [250000 rows x 3 columns],
           0    1    2
 0       123  192  234
 1       123  192  233
 2       122  190  231
 3       120  189  230
 4       117  189  229
 ...     ...  ...  ...
 249995    5    9   12
 249996    3    7   10
 249997    2    6    9
 249998    3    7   10
 249999    5    9   12

 [250000 rows x 3 columns],
         0   1  2
 0       4  27  7
 1       2  25  5
 2       2  25  5
 3       2  25  5
 4       3  25  5
 ...    ..  .. ..
 249995  3  33  5
 249996  3  33  5
 249997  3  33  5
 249998  3  33  5
 249999  5  35  7

 [250000 rows x 3 columns],
         0  1   2
 0       2  1  19
 1       2  1  19
 2       2  1  18
 3       2  1  20
 4       2  0  22
 ...    .. ..  ..
 249995  1  0  16
 249996  1  0  16
 249997  1  0  16
 249998  2  1  17
 249999  2  1  17

 [250000 rows x 3 columns],
           0    1    2
 0       242  248  234
 1       242  248  234
 2       242  248  234
 3       242  248  234
 4       242  248  234
 ...     ...  ...  ...
 249995  242  248  234
 249996  242  248  234
 249997  242  248  234
 249998  242  248  234
 249999  242  248  234

 [250000 rows x 3 columns],
           0    1    2
 0         7  136  154
 1        10  139  151
 2         3  134  138
 3        11  140  139
 4        27  152  152
 ...     ...  ...  ...
 249995   83   53   25
 249996  102   72   44
 249997   84   54   28
 249998   73   43   20
 249999   83   53   29

 [250000 rows x 3 columns],
          0   1    2
 0       45  58  106
 1       45  59  108
 2       45  59  108
 3       45  59  107
 4       44  59  108
 ...     ..  ..  ...
 249995  24  30   41
 249996  23  29   40
 249997  22  28   40
 249998  22  28   40
 249999  22  28   39

 [250000 rows x 3 columns],
          0   1   2
 0       21  17   8
 1       21  17   8
 2       22  18   9
 3       22  18   9
 4       21  17   8
 ...     ..  ..  ..
 249995  23  18  11
 249996  23  16   8
 249997  27  18   8
 249998  26  18   9
 249999  59  57  52

 [250000 rows x 3 columns],
          0   1   2
 0        9  16  47
 1       10  16  48
 2       10  16  48
 3       10  16  48
 4       10  16  48
 ...     ..  ..  ..
 249995  51  68  80
 249996  50  67  77
 249997  47  64  76
 249998  48  62  74
 249999  44  56  72

 [250000 rows x 3 columns],
          0   1    2
 0       61  21  109
 1       68  23  110
 2       76  26  111
 3       81  27  114
 4       85  30  114
 ...     ..  ..  ...
 249995  21  20   18
 249996  20  16   15
 249997  20  16   15
 249998  19  15   14
 249999  22  18   17

 [250000 rows x 3 columns],
           0   1    2
 0        43  68  118
 1        43  68  119
 2        43  68  119
 3        43  68  118
 4        42  67  118
 ...     ...  ..  ...
 249995  110  25   38
 249996  111  24   37
 249997  115  25   37
 249998  119  26   38
 249999  126  27   41

 [250000 rows x 3 columns],
          0   1   2
 0       79  87  90
 1       77  88  90
 2       80  90  91
 3       82  90  93
 4       81  89  92
 ...     ..  ..  ..
 249995   5  22  35
 249996   1   5  11
 249997   0   1   4
 249998   0   1   5
 249999   0   1   5

 [250000 rows x 3 columns],
         0  1   2
 0       7  4  87
 1       7  5  84
 2       6  3  80
 3       5  3  75
 4       5  3  71
 ...    .. ..  ..
 249995  1  1   1
 249996  1  1   1
 249997  1  1   1
 249998  1  1   1
 249999  1  1   1

 [250000 rows x 3 columns],
         0   1    2
 0       0  66  143
 1       0  66  143
 2       0  66  143
 3       0  67  144
 4       0  67  144
 ...    ..  ..  ...
 249995  1  19   65
 249996  1  19   65
 249997  1  19   65
 249998  1  19   65
 249999  1  19   65

 [250000 rows x 3 columns],
           0    1    2
 0        82   53   98
 1        74   53   99
 2        64   55  101
 3        58   60  107
 4        58   67  118
 ...     ...  ...  ...
 249995  199  204  223
 249996  197  202  221
 249997  196  201  220
 249998  195  200  219
 249999  193  198  217

 [250000 rows x 3 columns],
           0    1    2
 0       255  255  253
 1       254  253  251
 2       253  252  250
 3       255  255  253
 4       255  253  252
 ...     ...  ...  ...
 249995  255  255  255
 249996  254  254  254
 249997  253  253  253
 249998  252  252  252
 249999  252  252  252

 [250000 rows x 3 columns],
           0    1   2
 0        45    2  50
 1        48    2  55
 2        50    3  56
 3        51    2  57
 4        50    3  55
 ...     ...  ...  ..
 249995   90  124  27
 249996   46   69   5
 249997   68   94  15
 249998  116  148  31
 249999  119  146  46

 [250000 rows x 3 columns],
           0    1    2
 0       133   75   39
 1       135   77   45
 2       136   79   52
 3       145   86   59
 4       158   93   65
 ...     ...  ...  ...
 249995  227  185  156
 249996  237  194  162
 249997  232  189  158
 249998  236  193  162
 249999  234  191  161

 [250000 rows x 3 columns],
           0    1    2
 0       236  241  244
 1       239  244  248
 2       237  242  246
 3       240  245  251
 4       239  243  252
 ...     ...  ...  ...
 249995   15   26   30
 249996   14   25   29
 249997   57   66   71
 249998  161  166  172
 249999  241  246  252

 [250000 rows x 3 columns],
           0    1    2
 0       121  156  186
 1       107  141  169
 2        86  117  144
 3        86  114  137
 4       100  124  144
 ...     ...  ...  ...
 249995  180  183  192
 249996  180  183  192
 249997  178  181  190
 249998  179  182  191
 249999  182  185  194

 [250000 rows x 3 columns],
          0   1   2
 0       22  21  27
 1       23  22  28
 2       21  20  26
 3       22  21  27
 4       22  21  27
 ...     ..  ..  ..
 249995  21  21  21
 249996  21  21  21
 249997  21  21  21
 249998  21  21  21
 249999  21  21  21

 [250000 rows x 3 columns],
          0    1    2
 0       13  126  176
 1       13  128  173
 2       12  125  173
 3       12  125  173
 4       12  124  174
 ...     ..  ...  ...
 249995  45  100  103
 249996  46  103  105
 249997  47  105  106
 249998  49  105  107
 249999  47  102  105

 [250000 rows x 3 columns],
           0    1    2
 0        15   18   49
 1        14   17   48
 2        14   17   48
 3        14   17   48
 4        14   17   48
 ...     ...  ...  ...
 249995   60  120  127
 249996   66  123  129
 249997   76  131  133
 249998   87  139  141
 249999  100  151  150

 [250000 rows x 3 columns],
           0    1    2
 0       228  228  228
 1       229  229  229
 2       229  229  229
 3       229  229  229
 4       229  229  229
 ...     ...  ...  ...
 249995  163  163  163
 249996  163  163  163
 249997  163  163  163
 249998  163  163  163
 249999  163  163  163

 [250000 rows x 3 columns],
           0    1    2
 0       252  252  252
 1       255  255  255
 2       254  254  254
 3       255  255  255
 4       253  253  253
 ...     ...  ...  ...
 249995  255  255  255
 249996  255  255  255
 249997  255  255  255
 249998  255  255  255
 249999  255  255  254

 [250000 rows x 3 columns],
           0    1    2
 0         0    5   36
 1         0    5   36
 2         0    6   37
 3         0    3   35
 4         0    1   33
 ...     ...  ...  ...
 249995  163  210  234
 249996  160  207  234
 249997  159  206  236
 249998  157  206  238
 249999  158  207  239

 [250000 rows x 3 columns],
           0    1    2
 0       251  252  254
 1       251  252  254
 2       251  252  254
 3       251  252  254
 4       251  252  254
 ...     ...  ...  ...
 249995    1   27   73
 249996    1   28   75
 249997    1   26   70
 249998    1   25   68
 249999    1   25   68

 [250000 rows x 3 columns],
          0   1  2
 0       13   5  2
 1       13   5  2
 2       13   5  2
 3       13   5  2
 4       14   5  3
 ...     ..  .. ..
 249995  29   9  4
 249996  32  10  4
 249997  29   9  3
 249998  38  12  4
 249999  37  12  4

 [250000 rows x 3 columns],
           0    1    2
 0       137   41   55
 1       140   43   54
 2       142   51   56
 3       142   59   56
 4       140   61   54
 ...     ...  ...  ...
 249995  248  108  116
 249996  246  108  114
 249997  247  108  113
 249998  246  107  112
 249999  232  101  107

 [250000 rows x 3 columns],
           0    1    2
 0        46   49   37
 1        99   91   73
 2       131  108   84
 3       166  139  113
 4       160  134  110
 ...     ...  ...  ...
 249995    9   15   24
 249996    9   13   21
 249997    9   11   19
 249998    9    9   17
 249999    8    8   15

 [250000 rows x 3 columns],
          0    1  2
 0       51  102  9
 1       51  102  9
 2       51  102  9
 3       51  102  9
 4       51  102  9
 ...     ..  ... ..
 249995  57  109  9
 249996  57  109  9
 249997  57  109  9
 249998  57  109  9
 249999  57  109  9

 [250000 rows x 3 columns],
           0    1    2
 0       255  255  255
 1       255  255  255
 2       255  255  255
 3       255  255  255
 4       255  255  255
 ...     ...  ...  ...
 249995   98   98   98
 249996   98   98   98
 249997   98   98   98
 249998   99   99   99
 249999   98   98   98

 [250000 rows x 3 columns],
          0   1   2
 0       28  25  46
 1       25  23  44
 2        8   8  28
 3       16  18  37
 4       13  16  35
 ...     ..  ..  ..
 249995  62  59  40
 249996  67  65  45
 249997  79  77  57
 249998  65  62  43
 249999  72  69  50

 [250000 rows x 3 columns],
          0   1   2
 0       21  21  21
 1        9   9   9
 2        7   7   7
 3        4   4   4
 4        5   5   5
 ...     ..  ..  ..
 249995   6   6   6
 249996   6   6   6
 249997   6   6   6
 249998   5   5   5
 249999   5   5   5

 [250000 rows x 3 columns],
          0   1   2
 0       15  14  17
 1       15  13  16
 2       16  14  17
 3       16  14  17
 4       15  13  16
 ...     ..  ..  ..
 249995  26   3   7
 249996  26   3   9
 249997  26   3   9
 249998  26   3   9
 249999  25   3   6

 [250000 rows x 3 columns],
          0   1   2
 0       36  19   7
 1       44  22   7
 2       42  22  10
 3       48  24  11
 4       41  21   7
 ...     ..  ..  ..
 249995   7   3  17
 249996  10   2  18
 249997  14   3  20
 249998  13   4  19
 249999   8   2  17

 [250000 rows x 3 columns],
          0   1   2
 0       12  24  40
 1        4  15  31
 2        5  16  32
 3        5  16  32
 4        4  15  31
 ...     ..  ..  ..
 249995   3  13  25
 249996   5  15  24
 249997  13  22  42
 249998  11  20  52
 249999  25  39  71

 [250000 rows x 3 columns],
           0    1    2
 0        69  183  235
 1        69  183  235
 2        69  183  235
 3        69  183  235
 4        70  184  236
 ...     ...  ...  ...
 249995  240  192   22
 249996  240  192   22
 249997  240  192   22
 249998  240  192   22
 249999  240  192   22

 [250000 rows x 3 columns],
           0   1   2
 0       179  32  38
 1       182  31  38
 2       184  30  38
 3       184  30  38
 4       184  30  38
 ...     ...  ..  ..
 249995   86  46  19
 249996  108  63  27
 249997   93  51  23
 249998   76  38  15
 249999   77  45  20

 [250000 rows x 3 columns],
           0    1    2
 0       157  170   89
 1       165  178   94
 2       178  187  147
 3       187  202  150
 4       125  150   78
 ...     ...  ...  ...
 249995   25   21   25
 249996   23   21   24
 249997   24   22   25
 249998   23   21   24
 249999   23   21   24

 [250000 rows x 3 columns],
         0  1  2
 0       0  0  0
 1       0  0  0
 2       0  0  0
 3       0  0  0
 4       0  0  0
 ...    .. .. ..
 249995  0  0  0
 249996  0  0  0
 249997  0  0  0
 249998  0  0  0
 249999  0  0  0

 [250000 rows x 3 columns],
         0   1    2
 0       1  49  122
 1       1  48  121
 2       1  49  122
 3       1  48  120
 4       1  47  120
 ...    ..  ..  ...
 249995  7  26   52
 249996  8  28   55
 249997  7  27   54
 249998  7  26   52
 249999  7  27   52

 [250000 rows x 3 columns],
           0    1    2
 0       150  164  167
 1       150  164  167
 2       152  166  169
 3       155  169  172
 4       156  170  173
 ...     ...  ...  ...
 249995  132  147  154
 249996  133  148  155
 249997  135  150  157
 249998  135  150  157
 249999  135  150  157

 [250000 rows x 3 columns],
           0    1    2
 0       188  176  156
 1       186  173  153
 2       187  175  154
 3       185  172  153
 4       191  177  157
 ...     ...  ...  ...
 249995   70   67   53
 249996   72   68   53
 249997   70   66   52
 249998   68   65   51
 249999   72   68   52

 [250000 rows x 3 columns],
           0    1    2
 0         3  146  218
 1         4  146  217
 2         4  147  219
 3         4  149  219
 4         3  147  219
 ...     ...  ...  ...
 249995  149  137  128
 249996  146  133  125
 249997  145  133  125
 249998  145  136  126
 249999  148  138  129

 [250000 rows x 3 columns],
         0  1  2
 0       0  0  0
 1       0  0  0
 2       0  0  0
 3       0  0  0
 4       0  0  0
 ...    .. .. ..
 249995  0  0  0
 249996  0  0  0
 249997  0  0  0
 249998  0  0  0
 249999  0  0  0

 [250000 rows x 3 columns],
           0    1    2
 0       236  227  220
 1       236  227  220
 2       236  227  220
 3       236  227  220
 4       236  227  220
 ...     ...  ...  ...
 249995  124  171  186
 249996  125  170  185
 249997  128  169  185
 249998  124  170  185
 249999  121  169  183

 [250000 rows x 3 columns],
           0    1    2
 0       163  218  243
 1       163  218  244
 2       162  217  244

In [105]:
movie_gen = pd.Series(movie_genre)
movie_gen = movie_gen.str.replace('""', "")
gen = []
for i in range(len(movie_gen)):
    gen.append(movie_gen[i].rsplit(".",1)[0])
#movie_genr = movie_gen.tolist()
#movie_genr[1].rsplit(".",1)[0]

In [106]:
genr = pd.Series(gen)
genr

0       tt10009602
1       tt10034258
2       tt10055028
3       tt10075380
4       tt10075830
           ...
1186     tt9844368
1187     tt9848626
1188     tt9876582
1189     tt9883996
1190     tt9896916
Length: 1191, dtype: object

In [ ]:
mov_dict = {}
for i in range(len(genr)):
    mov_dict['id'] = genr[i]
    mov_dict['Genre_1'] = movie_dummy_1[movie_dummy_1['id'].isin(genr[i])]

In [108]:
movie_fil = movie_dummy_1[movie_dummy_1['id'].isin(genr)]
movie_fil['id']

136      tt7435570
200     tt10034258
460      tt6590506
540      tt3529404
735      tt3317652
           ...
3965    tt29702487
3966    tt14399126
3967    tt21862696
3968    tt13932976
3969    tt27838714
Name: id, Length: 1171, dtype: object

In [67]:
#Drop features within both missing and dropped datasets to avoid dummy variable collineraty 



features_to_drop = ['Gender_F', 'Education_Level_Graduate', 'Marital_Status_Married', 'Income_Category_Less than $40K', 'Card_Category_Blue']

bank_missing_df_dummy_dropped = bank_missing_df.drop(features_to_drop, axis=1)
bank_dropped_df_dummy_dropped = bank_dropped_df.drop(features_to_drop, axis=1)

In [68]:
#Assess new dataframe of dropped features bank_missing_df_dummy_dropped
bank_missing_df_dummy_dropped.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8101 entries, 0 to 8100
Data columns (total 33 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Customer_Age                   8101 non-null   int64
 1   Dependent_count                8101 non-null   int64
 2   Months_on_book                 8101 non-null   int64
 3   Total_Relationship_Count       8101 non-null   int64
 4   Months_Inactive_12_mon         8101 non-null   int64
 5   Contacts_Count_12_mon          8101 non-null   int64
 6   Credit_Limit                   8101 non-null   float64
 7   Total_Revolving_Bal            8101 non-null   int64
 8   Avg_Open_To_Buy                8101 non-null   float64
 9   Total_Amt_Chng_Q4_Q1           8101 non-null   float64
 10  Total_Trans_Amt                8101 non-null   int64
 11  Total_Trans_Ct                 8101 non-null   int64
 12  Total_Ct_Chng_Q4_Q1            8101 non-null   float64
 13  Avg_Utilization_Ratio          8101 non-null   float64
 14  Attrition_Flag                 8101 non-null   int64
 15  Gender_M                       8101 non-null   int64
 16  Education_Level_College        8101 non-null   int64
 17  Education_Level_Doctorate      8101 non-null   int64
 18  Education_Level_High School    8101 non-null   int64
 19  Education_Level_Post-Graduate  8101 non-null   int64
 20  Education_Level_Uneducated     8101 non-null   int64
 21  Education_Level_missing        8101 non-null   int64
 22  Marital_Status_Divorced        8101 non-null   int64
 23  Marital_Status_Single          8101 non-null   int64
 24  Marital_Status_missing         8101 non-null   int64
 25  Income_Category_$120K +        8101 non-null   int64
 26  Income_Category_$40K - $60K    8101 non-null   int64
 27  Income_Category_$60K - $80K    8101 non-null   int64
 28  Income_Category_$80K - $120K   8101 non-null   int64
 29  Income_Category_missing        8101 non-null   int64
 30  Card_Category_Gold             8101 non-null   int64
 31  Card_Category_Platinum         8101 non-null   int64
 32  Card_Category_Silver           8101 non-null   int64
dtypes: float64(5), int64(28)
memory usage: 2.1 MB

In [69]:
bank_missing_df_dummy_dropped.head()

,Customer_Age,Dependent_count,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,...,Marital_Status_Single,Marital_Status_missing,Income_Category_$120K +,Income_Category_$40K - $60K,Income_Category_$60K - $80K,Income_Category_$80K - $120K,Income_Category_missing,Card_Category_Gold,Card_Category_Platinum,Card_Category_Silver
0,54,1,36,1,3,3,3723.0,1728,1995.0,0.595,...,1,0,0,0,0,0,1,0,0,0
1,58,4,48,1,4,3,5396.0,1803,3593.0,0.493,...,0,0,0,0,0,0,1,0,0,0
2,45,4,36,6,1,3,15987.0,1648,14339.0,0.732,...,1,0,0,0,0,0,0,1,0,0
3,34,2,36,4,3,4,3625.0,2517,1108.0,1.158,...,1,0,0,0,0,0,0,0,0,0
4,49,2,39,5,3,4,2720.0,1926,794.0,0.602,...,0,0,0,1,0,0,0,0,0,0

In [70]:
bank_missing_df_dummy_dropped.shape

(8101, 33)

In [71]:
#Assess new dataframe of dropped features bank_dropped_df_dummy_dropped
bank_dropped_df_dummy_dropped.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5690 entries, 3 to 8100
Data columns (total 30 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Customer_Age                   5690 non-null   int64
 1   Dependent_count                5690 non-null   int64
 2   Months_on_book                 5690 non-null   int64
 3   Total_Relationship_Count       5690 non-null   int64
 4   Months_Inactive_12_mon         5690 non-null   int64
 5   Contacts_Count_12_mon          5690 non-null   int64
 6   Credit_Limit                   5690 non-null   float64
 7   Total_Revolving_Bal            5690 non-null   int64
 8   Avg_Open_To_Buy                5690 non-null   float64
 9   Total_Amt_Chng_Q4_Q1           5690 non-null   float64
 10  Total_Trans_Amt                5690 non-null   int64
 11  Total_Trans_Ct                 5690 non-null   int64
 12  Total_Ct_Chng_Q4_Q1            5690 non-null   float64
 13  Avg_Utilization_Ratio          5690 non-null   float64
 14  Attrition_Flag                 5690 non-null   int64
 15  Gender_M                       5690 non-null   int64
 16  Education_Level_College        5690 non-null   int64
 17  Education_Level_Doctorate      5690 non-null   int64
 18  Education_Level_High School    5690 non-null   int64
 19  Education_Level_Post-Graduate  5690 non-null   int64
 20  Education_Level_Uneducated     5690 non-null   int64
 21  Marital_Status_Divorced        5690 non-null   int64
 22  Marital_Status_Single          5690 non-null   int64
 23  Income_Category_$120K +        5690 non-null   int64
 24  Income_Category_$40K - $60K    5690 non-null   int64
 25  Income_Category_$60K - $80K    5690 non-null   int64
 26  Income_Category_$80K - $120K   5690 non-null   int64
 27  Card_Category_Gold             5690 non-null   int64
 28  Card_Category_Platinum         5690 non-null   int64
 29  Card_Category_Silver           5690 non-null   int64
dtypes: float64(5), int64(25)
memory usage: 1.3 MB

In [72]:
bank_dropped_df_dummy_dropped.head()

,Customer_Age,Dependent_count,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,...,Education_Level_Uneducated,Marital_Status_Divorced,Marital_Status_Single,Income_Category_$120K +,Income_Category_$40K - $60K,Income_Category_$60K - $80K,Income_Category_$80K - $120K,Card_Category_Gold,Card_Category_Platinum,Card_Category_Silver
3,34,2,36,4,3,4,3625.0,2517,1108.0,1.158,...,0,0,1,0,0,0,0,0,0,0
4,49,2,39,5,3,4,2720.0,1926,794.0,0.602,...,0,0,0,0,1,0,0,0,0,0
5,60,0,45,5,2,4,1438.3,648,790.3,0.477,...,0,0,0,0,0,0,0,0,0,0
8,30,0,36,3,3,2,2550.0,1623,927.0,0.650,...,0,0,0,0,0,0,0,0,0,0
9,33,3,36,5,2,3,1457.0,0,1457.0,0.677,...,0,0,1,0,0,0,0,0,0,0

In [73]:
bank_dropped_df_dummy_dropped.shape

(5690, 30)

## 4.5 Create Train_Test Split & Preprocess Training Data

### 4.5.1 Create Train_Test_Split

For implementation of future modeling, a train_test_split is created for both the missing and dropped datasets. The test size is arbritraily set for a 70/30 split.

In [74]:
#Creating train_test_split for both missing and dropped bank churn datasets.
#Test size arbritarily set at 70/30 split for training and future model performance and testing.

X_missing = bank_missing_df_dummy_dropped.drop(['Attrition_Flag'], axis=1)
y_missing = bank_missing_df_dummy_dropped['Attrition_Flag']
X_dropped = bank_dropped_df_dummy_dropped.drop(['Attrition_Flag'], axis=1)
y_dropped = bank_dropped_df_dummy_dropped['Attrition_Flag']


X_train_missing, X_test_missing, y_train_missing, y_test_missing = train_test_split(X_missing, y_missing, test_size=0.30, random_state = random_number) 
X_train_dropped, X_test_dropped, y_train_dropped, y_test_dropped = train_test_split(X_dropped, y_dropped, test_size=0.30, random_state= random_number)

### 4.5.2 Apply StandardScaler() for Training Data

In order to create equal distributions with mean centered at 0 between each of the features for future modeling, a standard scaler object is created and defined for training for both datasets. The same scaler is also applied for transforming X_test datasets for consistency and future modeling.

In [75]:
# Created function for fitting and transforming scaler object for X_train of both datasets and then transform X_test for both datasets
def scaling(train , test):
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(train)
    X_test_scaled = scaler.transform(test)
    
    return X_train_scaled, X_test_scaled

In [76]:
X_train_scaled_missing , X_test_scaled_missing = scaling(X_train_missing, X_test_missing)

In [77]:
X_train_scaled_dropped , X_test_scaled_dropped = scaling(X_train_dropped, X_test_dropped)

Reviewing as well the above arrays created after scaling the trained datasets.

In [78]:
#Reviewing of X_train_scaled_missing and dropped as well as X_test_scaled_missing and dropped
X_train_scaled_missing

array([[-0.41349078,  1.28797953, -1.35293228, ..., -0.11017496,
        -0.04408862, -0.24090084],
       [ 1.45572316, -1.03949649,  0.0039595 , ..., -0.11017496,
        -0.04408862, -0.24090084],
       [ 0.33419479,  1.28797953, -0.85951709, ..., -0.11017496,
        -0.04408862, -0.24090084],
       ...,
       [ 0.08496627,  2.06380487,  0.6207285 , ..., -0.11017496,
        -0.04408862, -0.24090084],
       [ 0.08496627,  0.51215419,  0.8674361 , ..., -0.11017496,
        -0.04408862, -0.24090084],
       [ 1.58033743, -1.03949649,  2.10097409, ..., -0.11017496,
        -0.04408862, -0.24090084]])

In [79]:
X_test_scaled_missing

array([[ 1.33110890e+00, -2.63671151e-01,  3.95950466e-03, ...,
        -1.10174961e-01, -4.40886190e-02, -2.40900841e-01],
       [-4.13490784e-01,  1.28797953e+00, -2.42748093e-01, ...,
        -1.10174961e-01, -4.40886190e-02, -2.40900841e-01],
       [-1.90886194e+00, -1.03949649e+00, -1.72299368e+00, ...,
        -1.10174961e-01, -4.40886190e-02, -2.40900841e-01],
       ...,
       [-2.88876521e-01, -1.03949649e+00, -2.42748093e-01, ...,
        -1.10174961e-01, -4.40886190e-02,  4.15108555e+00],
       [ 2.09580531e-01,  5.12154188e-01, -7.36163289e-01, ...,
        -1.10174961e-01, -4.40886190e-02, -2.40900841e-01],
       [ 3.34194794e-01,  1.28797953e+00,  8.67436097e-01, ...,
        -1.10174961e-01, -4.40886190e-02, -2.40900841e-01]])

In [80]:
X_train_scaled_dropped

array([[-1.50889427,  0.52736863, -0.98537568, ..., -0.10446868,
        -0.03884166, -0.23532724],
       [-0.63893519, -1.02914063, -0.48336093, ..., -0.10446868,
        -0.03884166, -0.23532724],
       [ 0.35530376,  2.08387789, -0.10684986, ...,  9.5722467 ,
        -0.03884166, -0.23532724],
       ...,
       [ 1.47382257,  1.30562326,  2.15221653, ..., -0.10446868,
        -0.03884166, -0.23532724],
       [ 1.22526283, -1.02914063,  1.02268333, ..., -0.10446868,
        -0.03884166, -0.23532724],
       [-1.50889427, -0.250886  , -2.86793101, ..., -0.10446868,
        -0.03884166, -0.23532724]])

In [81]:
X_test_scaled_dropped

array([[-1.13605466,  1.30562326,  0.01865382, ..., -0.10446868,
        -0.03884166, -0.23532724],
       [ 0.35530376,  1.30562326,  0.01865382, ..., -0.10446868,
        -0.03884166, -0.23532724],
       [ 0.85242323,  0.52736863,  1.3991944 , ..., -0.10446868,
        -0.03884166, -0.23532724],
       ...,
       [-0.88749493, -0.250886  , -0.60886462, ..., -0.10446868,
        -0.03884166, -0.23532724],
       [-0.26609559,  1.30562326, -0.73436831, ..., -0.10446868,
        -0.03884166, -0.23532724],
       [-1.26033453,  0.52736863,  0.01865382, ..., -0.10446868,
        -0.03884166, -0.23532724]])

Now that arrays have been created for X_train, X_test, y_train, and y_test for each missing and dropped datasets, these will be utilized in the next steps regarding assessing model performance.

## 4.6 Save data

In [82]:
#Missing X_train and y_train set shape
print(f"X_train_scaled_missing shape: {X_train_scaled_missing.shape} and y_train_missing shape: {y_train_missing.shape}")

X_train_scaled_missing shape: (5670, 32) and y_train_missing shape: (5670,)

In [83]:
#Missing X_test and y_test set shape
print(f"X_test_scaled_missing shape: {X_test_scaled_missing.shape} and y_test_missing shape: {y_test_missing.shape}")

X_test_scaled_missing shape: (2431, 32) and y_test_missing shape: (2431,)

In [84]:
#Dropped X_train and y_train set shape
print(f"X_train_scaled_dropped shape: {X_train_scaled_dropped.shape} and y_train_dropped shape: {y_train_dropped.shape}")

X_train_scaled_dropped shape: (3983, 29) and y_train_dropped shape: (3983,)

In [85]:
#Dropped X_test and y_test set shape
print(f"X_test_scaled_dropped shape: {X_test_scaled_dropped.shape} and y_test_dropped shape: {y_test_dropped.shape}")

X_test_scaled_dropped shape: (1707, 29) and y_test_dropped shape: (1707,)

In [86]:
#Created dataframes for the new and respectice X_train_scaled and y_test arrays
#Code for setting arrays as df and then saving to .csv found on https://stackoverflow.com/questions/6081008/dump-a-numpy-array-into-a-csv-file
df_X_train_scaled_missing = pd.DataFrame(X_train_scaled_missing)
df_y_train_missing = pd.DataFrame(y_train_missing)
df_X_test_scaled_missing = pd.DataFrame(X_test_scaled_missing)
df_y_test_missing = pd.DataFrame(y_test_missing)
df_X_train_scaled_dropped = pd.DataFrame(X_train_scaled_dropped)
df_y_train_dropped = pd.DataFrame(y_train_dropped)
df_X_test_scaled_dropped = pd.DataFrame(X_test_scaled_dropped)
df_y_test_dropped = pd.DataFrame(y_test_dropped)

In [87]:
# save the new datasets to new csv files for future model implementation
datapath = 'C:/Users/tpooz/OneDrive/Desktop/Data_Science_BootCamp_2023/SpringBoard_Github/Bank-Churnrate/0_Datasets/Test_Train_Sets'
df_X_train_scaled_missing.to_csv('C:/Users/tpooz/OneDrive/Desktop/Data_Science_BootCamp_2023/SpringBoard_Github/Bank-Churnrate/0_Datasets/Test_Train_Sets/X_train_scaled_missing.csv', header=True, index=True) 
df_y_train_missing.to_csv('C:/Users/tpooz/OneDrive/Desktop/Data_Science_BootCamp_2023/SpringBoard_Github/Bank-Churnrate/0_Datasets/Test_Train_Sets/y_train_missing.csv', header=True, index=False) 
df_X_test_scaled_missing.to_csv('C:/Users/tpooz/OneDrive/Desktop/Data_Science_BootCamp_2023/SpringBoard_Github/Bank-Churnrate/0_Datasets/Test_Train_Sets/X_test_scaled_missing.csv', header=True, index=False)
df_y_test_missing.to_csv('C:/Users/tpooz/OneDrive/Desktop/Data_Science_BootCamp_2023/SpringBoard_Github/Bank-Churnrate/0_Datasets/Test_Train_Sets/y_test_missing.csv', header=True, index=False)
df_X_train_scaled_dropped.to_csv('C:/Users/tpooz/OneDrive/Desktop/Data_Science_BootCamp_2023/SpringBoard_Github/Bank-Churnrate/0_Datasets/Test_Train_Sets/X_train_scaled_dropped.csv', header=True, index=False)
df_y_train_dropped.to_csv('C:/Users/tpooz/OneDrive/Desktop/Data_Science_BootCamp_2023/SpringBoard_Github/Bank-Churnrate/0_Datasets/Test_Train_Sets/y_train_dropped.csv', header=True, index=False)
df_X_test_scaled_dropped.to_csv('C:/Users/tpooz/OneDrive/Desktop/Data_Science_BootCamp_2023/SpringBoard_Github/Bank-Churnrate/0_Datasets/Test_Train_Sets/X_test_scaled_dropped.csv', header=True, index=False)
df_y_test_dropped.to_csv('C:/Users/tpooz/OneDrive/Desktop/Data_Science_BootCamp_2023/SpringBoard_Github/Bank-Churnrate/0_Datasets/Test_Train_Sets/y_test_dropped.csv', header=True, index=False)

## 4.7 Summary

After applying scikit learns train_test_split and StandardScaler in order to create arbitray 70/30 splits of the datasets for both the missing and dropped bank churn datasets, these will be applied in the next steps regarding model performance. Some notes regarding the steps involved include avoiding the dummy variable trap or multicollineratiy between one-hot encoded feature variables by instead apply only k-1 feature values for the categorical variables. And a function was also created in order to apply the StandardScaler() object for the two different datasets as otherwise the object could not fit_transform for a different dataset after already being applied to a previous one. 

Notes to keep in mind is especially for the dropped dataset, the training data because of starting being dropped for missing values has further decreased for a training set of 3983 observations. This further decrease in terms of observations might affect different model performance.